use_frameworks!

target 'FayeCilentSwift_Example' do
  pod 'FayeCilentSwift', :path => '../'

  target 'FayeCilentSwift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
